name: ./GON/envs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cudatoolkit=11.1.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2020.2
  - jpeg=9b
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuv=1.41.0
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1k
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.7.10
  - python_abi=3.7
  - pytorch=1.8.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.59.0
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - adabelief-pytorch==0.2.1
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==20.3.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - colorama==0.4.4
    - fsspec==0.8.7
    - future==0.18.2
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - idna==2.10
    - importlib-metadata==3.7.3
    - lmdb==1.1.1
    - markdown==3.3.4
    - multidict==5.1.0
    - oauthlib==3.1.0
    - pillow-simd==7.0.0.post3
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==1.2.5
    - pyyaml==5.3.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.2.0
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - yarl==1.6.3
    - zipp==3.4.1

